### ISSUE TITLE
wrong auto network interface selection when vmware and virtualbox are installed on Windows

### ISSUE THREAD

**Issue by hoatle** [teracyhq-incubator/teracy-dev-essential#27]
```bash
F:/teracy/iorad-dev/extensions/teracy-dev-essential/lib/teracy-dev-essential/config/networks.rb:28:in `block in configure_networks'

[TeracyDevEssential::Config::Networks][DEBUG]: configure_networks: bridge_interface: NetConnectionID  

Wireless Network Connection

VirtualBox Host-Only Network

VMware Network Adapter VMnet1

VMware Network Adapter VMnet8
F:/teracy/iorad-dev/extensions/teracy-dev-essential/lib/teracy-dev-essential/config/networks.rb:30:in `block in configure_networks'

[TeracyDevEssential::Config::Networks][DEBUG]: config.vm.networks: [[:public_network, {:id=>"0-public_network-v05-compat-0", :protocol=>"tcp", :mac=>"080027487722", :bridge=>"NetConnectionID                \n\nWireless Network Connection    \n\nVirtualBox Host-Only Network   \n\nVMware Network Adapter VMnet1  \n\nVMware Network Adapter VMnet8"}]]
F:/teracy/iorad-dev/extensions/teracy-dev-essential/lib/teracy-dev-essential/config/networks.rb:40:in `block in configure_networks'

Current machine states:

iorad.local               running (virtualbox)

The VM is running. To stop this VM, you can run `vagrant halt` to
shut it down forcefully, or you can run `vagrant suspend` to simply
suspend the virtual machine. In either case, to restart it again,
simply run `vagrant up`.

Administrator@CBS85CFXNI4FWJ5 /cygdrive/f/teracy/iorad-dev
```

**Comment by hoatle** [comment]
move to next sprint instead

**Comment by hoatle** [comment]
assigned to @hoavt to verify this
