### ISSUE TITLE
vagrant-gatling-rsync does not work on vagrant 2.2.5 and 2.2.6

### ISSUE THREAD

**Issue by hieptranquoc** [teracyhq-incubator/teracy-dev-essential#57]
https://github.com/teracyhq-incubator/teracy-dev-essential/pull/56.

vagrant-gatling-rsync plugin error with vagrant version 2.2.4 -> 2.2.6.

**Comment by hoatle** [comment]
vagrant-gatling-rsync does not work on vagrant 2.2.5 and 2.2.6

```
/opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/plugins/synced_folders/rsync/helper.rb:25:in `exclude_to_regexp': wrong number of arguments (given 2, expected 1) (ArgumentError)
	from /Users/hoatle/.vagrant.d/gems/2.4.9/gems/vagrant-gatling-rsync-0.9.0/lib/vagrant-gatling-rsync/command/rsync_auto.rb:70:in `block (3 levels) in execute'
	from /Users/hoatle/.vagrant.d/gems/2.4.9/gems/vagrant-gatling-rsync-0.9.0/lib/vagrant-gatling-rsync/command/rsync_auto.rb:69:in `each'
	from /Users/hoatle/.vagrant.d/gems/2.4.9/gems/vagrant-gatling-rsync-0.9.0/lib/vagrant-gatling-rsync/command/rsync_auto.rb:69:in `block (2 levels) in execute'
	from /Users/hoatle/.vagrant.d/gems/2.4.9/gems/vagrant-gatling-rsync-0.9.0/lib/vagrant-gatling-rsync/command/rsync_auto.rb:54:in `each'
	from /Users/hoatle/.vagrant.d/gems/2.4.9/gems/vagrant-gatling-rsync-0.9.0/lib/vagrant-gatling-rsync/command/rsync_auto.rb:54:in `block in execute'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/plugin/v2/command.rb:238:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/plugin/v2/command.rb:232:in `each'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/plugin/v2/command.rb:232:in `with_target_vms'
	from /Users/hoatle/.vagrant.d/gems/2.4.9/gems/vagrant-gatling-rsync-0.9.0/lib/vagrant-gatling-rsync/command/rsync_auto.rb:38:in `execute'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/cli.rb:66:in `execute'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/environment.rb:290:in `cli'
	from /Users/hoatle/teracy-dev/workspace/teracy-dev/extensions/teracy-dev-essential/lib/teracy-dev-essential/config/rsync_recovery.rb:151:in `block (2 levels) in configure_trigger_after'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/plugin/v2/trigger.rb:320:in `execute_ruby'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/plugin/v2/trigger.rb:173:in `block in fire'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/plugin/v2/trigger.rb:142:in `each'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/plugin/v2/trigger.rb:142:in `fire'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/plugin/v2/trigger.rb:74:in `fire_triggers'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/machine.rb:214:in `action'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
```

**Comment by hoatle** [comment]
so we force to use rsync-auto instead on vagrant 2.2.5 and 2.2.6, for 2.2.7, we'll check on this later to see if we need to force this.

**Comment by hoatle** [comment]
verified, closed.
